weights:
  denial_penalty: 2.0
  cluster_weights:
    auth_required: 1.5
    coding_error: 1.2
    expired_coverage: 1.0
    duplicate_claim: 0.8
  slow_payers:
    P001: 1.5
    P002: 1.2
  complex_cpt:
    "99285": 2.0
    "99284": 1.8
  claim_age_weight: 0.02
  default_score: 1.0

team_rules:
  Team_Authorization: ["auth_required"]
  Team_CodingError: ["coding_error"]
  Team_ClaimError: ["duplicate_claim"]
  Team_CoverageIssue: ["expired_coverage"]
  Team_Medical_Necessity: ["medically necessary"]

# --- ADD THIS NEW SECTION ---
label_mapping:
  auth_required:
    - "Authorization"
    - "Pre-certification"
    - "Referral"
    - "Auth number"
  coding_error:
    - "Procedure Inconsistent"
    - "Invalid Procedure Code"
  medical_necessity:
    - "Medically Necessary"
  expired_coverage:
    - "Patient Not Covered"
    - "Coverage Terminated"
  duplicate_claim:
    - "Duplicate Claim"