import pandas as pd

mock_cluster_input = pd.DataFrame(
    {
        "claim_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        "denial_reason": [
            "Missing prior authorization",
            "Expired coverage",
            "Duplicate claim",
            "Missing prior authorization",
            "Coding error",
            "Invalid modifier",
            "Benefit max reached",
            "Late filing",
            "Missing prior authorization",
            "Expired coverage",
        ],
        "followup_notes": [
            "Need auth letter",
            "Plan inactive",
            "Already submitted",
            "Submit form again",
            "Invalid CPT code",
            "Modifier required",
            "Exceeds plan limit",
            "File within 90 days",
            "Request review",
            "Re-enrollment needed",
        ],
        "payer_id": [
            "P001",
            "P002",
            "P001",
            "P003",
            "P002",
            "P001",
            "P002",
            "P003",
            "P001",
            "P003",
        ],
        "provider_type": [
            "Hospital",
            "Clinic",
            "Hospital",
            "Clinic",
            "Hospital",
            "Clinic",
            "Hospital",
            "Clinic",
            "Hospital",
            "Clinic",
        ],
        "plan_type": [
            "Private",
            "Medicaid",
            "Private",
            "Medicare",
            "Private",
            "Medicaid",
            "Private",
            "Medicare",
            "Private",
            "Medicaid",
        ],
        "claim_type": [
            "Professional",
            "Institutional",
            "Professional",
            "Professional",
            "Institutional",
            "Institutional",
            "Professional",
            "Institutional",
            "Professional",
            "Professional",
        ],
        "billing_provider_specialty": [
            "Oncology",
            "Cardiology",
            "Oncology",
            "Neurology",
            "Cardiology",
            "Pediatrics",
            "Oncology",
            "Neurology",
            "Cardiology",
            "Pediatrics",
        ],
        "facility_code": [11, 22, 11, 11, 22, 11, 22, 22, 11, 22],
        "diagnosis_code": [
            "Z00.00",
            "R51.9",
            "Z00.00",
            "E11.9",
            "R51.9",
            "J20.9",
            "M54.5",
            "Z00.00",
            "E11.9",
            "R51.9",
        ],
        "prior_authorization": ["Y", "N", "Y", "Y", "N", "N", "Y", "N", "Y", "N"],
        "procedure_code": [
            99213,
            99214,
            99215,
            99203,
            85025,
            87070,
            99203,
            85027,
            99214,
            85025,
        ],
        "patient_age": [45, 50, 38, 60, 42, 28, 35, 47, 53, 31],
        "total_charge_amount": [
            500.0,
            750.0,
            620.0,
            700.0,
            430.0,
            480.0,
            690.0,
            510.0,
            610.0,
            455.0,
        ],
        "days_to_submission": [2, 3, 1, 4, 2, 5, 2, 3, 1, 4],
        "accident_indicator": [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        "denied": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    }
)
